### ISSUE TITLE
Steps for Building without Cocoa Pods

### ISSUE THREAD

**Issue by indivisable** [airbnb/lottie-react-native#31]
This may be helpful to others as it took me a few tries to get this working when integrating the library into an existing project (RN 0.36.0):

**Step 1)** Manually add babel-presets to **package.json**

```
  "devDependencies": {
    "babel-preset-airbnb": "^1.1.1",
    "babel-plugin-module-resolver": "^2.3.0",
```

**Step 2)** Install the React Native wrapper:

`yarn add lottie-react-native` OR `npm -i lottie-react-native --save`

**Step 3)** Install and Link to your project

`yarn install` OR `npm install`
`react-native link lottie-react-native`

**Step 4)** Clone the lottie-ios (Objective-C) library (pref outside your project path)

`git clone https://github.com/airbnb/lottie-ios.git`

**Step 5)** Drag and drop your project into the Libraries Folder (in XCode)

![image](https://cloud.githubusercontent.com/assets/22860891/22581467/d2c8a308-e9a5-11e6-8266-537918a922e8.png)

**Step 6)** Add to **Embedded Binaries and Linked Frameworks** (of main project)

![image](https://cloud.githubusercontent.com/assets/22860891/22581411/54f0e940-e9a5-11e6-96bb-2d9f8d99ed20.png)

**Step 7)** Clean and Rebuild your project in XCode

**Step 8)** Start the server and load app 

`yarn start` OR `npm start`

If get some errors try to flush cache etc.

```
 watchman watch-del-all
 rm -rf $TMPDIR/react-native-packager-*
 npm start -- --reset-cache
```
@AlexDM0 @lelandrichardson Thanks for the help 🥇 

References: #19 #25

**Comment by kainolophobia** [comment]
If anyone is having trouble getting the lottie-ios project to build properly, I used [this commit from 5 days ago](https://github.com/airbnb/lottie-ios/tree/5159b2ce3856cfe6704367cbed45ab649d514f6a) when this issue was created.

**Comment by lelandrichardson** [comment]
This should be fixed now. Please let me know if it's not!

**Comment by olle-moren-schibsted** [comment]
I still get the `'Lottie/Lottie.h' file not found` inside `node_modules/lottie-react-native/lib/ios/LottieReactNative/LRNContainerView.h` having RN: 0.39.2
I've manually dragged both `lottie-react-native` and a separately cloned `lottie-ios` into Xcode as described in earlier posts.

**Comment by indivisable** [comment]
@olle-moren-schibsted are you sure you are using the latest 1.0.6?

**Comment by olle-moren-schibsted** [comment]
@indivisable yes, the `package.json` has `"dependencies": {"lottie-react-native": "^1.0.6"}` auto injected.

**Comment by dslounge** [comment]
- "react-native": "0.41.2",
- "lottie-react-native": "1.0.6",
- not using cocoapods

Just chiming in to add that I also get the `'Lottie/Lottie.h' file not found` issue. I also can't run the project via `react-native run-ios` either, I get this issue:

```
Undefined symbols for architecture x86_64:
  "_OBJC_CLASS_$_LOTLayerGroup", referenced from:
      objc-class-ref in libLottie.a(LOTComposition.o)
      objc-class-ref in libLottie.a(LOTAsset.o)
ld: symbol(s) not found for architecture x86_64
```

I'm just starting the process of looking through issues to find an answer, but just wanted to let you know that it happened to me.

**Comment by balsloev** [comment]
My problem was that I had added all content from `Libraries > Lottie > Products` to `Link Binary With Libraries`. I just had to add `Lottie.framework (Debug-iphonesimulator)`.
