### ISSUE TITLE
duplicate interface definition for class 'RCTView'

### ISSUE THREAD

**Issue by zawarudo** [airbnb/lottie-react-native#32]
`
In file included from ./node_modules/lottie-react-native/lib/ios/LottieReactNative/LottieContainerView.m:9:
In file included from ./node_modules/lottie-react-native/lib/ios/LottieReactNative/LottieContainerView.h:12:
../../../react-native/React/Views/RCTView.h:21:1: error: duplicate interface definition for class 'RCTView'
`

lottie-react-native: 1.0.1,
react-native 0.41.0,

Full error log: https://gist.github.com/zawarudo/ec17df88555b58a483ed81c86e98e171

Similar to
https://github.com/airbnb/react-native-maps/issues/937
https://github.com/airbnb/react-native-maps/issues/957

**Comment by ferologics** [comment]
fixed in #28

**Comment by kyle-ssg** [comment]
Unless I'm missing something, the above PR didn't solve the problem. I'm still getting the issue mentioned on 0.40.0+ projects

**Comment by lelandrichardson** [comment]
You're getting this error because CocoaPods is referencing react native from the cocoapods specs repository, and not your local node_modules folder.  I'm assuming this is happening because you're including react into your project as a static library (not with cocoapods), but including Lottie with cocoapods.

I'm hoping to set this project up a little bit differently so it is easier to include as a static library ASAP. At the moment, though, you can add LottieReactNative.xcodeproject as a static library, and then also add Lottie as a static library, or you can change your project to install react via cocoapods.

Apologies for the back and forth on this

**Comment by zawarudo** [comment]
@lelandrichardson 

Thanks for the clarification, I'm still having trouble understanding what you mean however.

>or you can change your project to install react via cocoapods.
Should I ommit the react entry to allow CocoaPods to handle the installation?
Below is my PodFile and output when installing.


**Podfile**
> 
> target "Example" do
> 
>   pod 'React', :path => '../node_modules/react-native'
> 
>   pod 'BVLinearGradient', :path => '../node_modules/react-native-linear-gradient'
> 
>   pod 'lottie-react-native', :path => '../node_modules/lottie-react-native'
> 
> end

**Output**
> 
> Fetching podspec for `BVLinearGradient` from `../node_modules/react-native-linear-gradient`
> Fetching podspec for `React` from `../node_modules/react-native`
> Fetching podspec for `lottie-react-native` from `../node_modules/lottie-react-native`
> Downloading dependencies
> Using BVLinearGradient (2.0.0)
> Using React (0.41.1)
> Using lottie-ios (1.0.0)
> Using lottie-react-native (1.0.1)
> Generating Pods project
> Integrating client project
> Sending stats
> Pod installation complete! There are 3 dependencies from the Podfile and 4 total pods installed.


**Package.json**

> "dependencies": {
>     "bluebird": "^3.3.5",
>     "es6-symbol": "^3.0.2",
>     "event-emitter": "^0.3.4",
>     "immutable": "^3.7.6",
>     "lodash": "^4.17.4",
>     "lottie-react-native": "^1.0.1",
>     "moment": "^2.12.0",
>     "react": "^15.4.2",
>     "react-dom": "^15.4.2",
>     "react-native": "0.41.1",
>     "react-native-camera": "^0.6.0",
>     "react-native-linear-gradient": "^2.0.0",
>     "react-native-vector-icons": "^4.0.0",
>     "react-redux": "^5.0.2",
>     "redux": "^3.4.0",
>     "redux-logger": "^2.6.1",
>     "redux-loop": "^2.1.0",
>     "redux-promise": "^0.5.3",
>     "redux-thunk": "^2.0.1",
>     "standard-http-error": "^2.0.0"
>   },
>   "devDependencies": {
>     "babel-core": "^6.22.1",
>     "babel-eslint": "^7.1.0",
>     "babel-jest": "^18.0.0",
>     "babel-polyfill": "^6.9.0",
>     "babel-preset-react-native": "^1.9.1",
>     "babel-preset-stage-0": "^6.5.0",
>     "babel-register": "^6.22.0",
>     "enzyme": "^2.2.0",
>     "eslint": "^3.10.1",
>     "eslint-plugin-babel": "^4.0.1",
>     "eslint-plugin-react": "^6.7.1",
>     "fetch-mock": "^5.5.0",
>     "istanbul": "^0.4.5",
>     "jest": "^18.1.0",
>     "react-addons-test-utils": "^15.4.2",
>     "react-native-mock": "^0.2.9",
>     "react-test-renderer": "^15.4.2",
>     "rimraf": "^2.5.2"
>   }

**Comment by offwhite** [comment]
I'm also struggling with this issue - Linked [Lottie-ios](https://github.com/airbnb/lottie-ios) and lottie-react-native as static libraries but still getting the same header errors.

would love some clarity here @lelandrichardson - also, thanks for this, I think it's going to be a fantastically useful library.

**Comment by AdriVig** [comment]
I'm having the same issue after linked lottie-react-native as static library in Xcode

Xcode : 8.2.1
RN : 0.40.0
lottie-react-native : 1.0.1

![untitled](https://cloud.githubusercontent.com/assets/9379198/22645753/de295c9a-ec68-11e6-9449-73e59985f712.png)
![untitled2](https://cloud.githubusercontent.com/assets/9379198/22645789/147259e6-ec69-11e6-8e2a-b05e1ac232f3.png)

**Comment by offwhite** [comment]
I fixed this with some minimal tweaks to the imports, put a PR in for it here: https://github.com/airbnb/lottie-react-native/pull/41

**Comment by jondot** [comment]
To provide some more specific steps for what @lelandrichardson suggested, here's how to successfully use Lottie and `lottie-react-native` with the latest react native, this is in addition to what @offwhite just suggested.


* First, install `lottie-react-native` in the normal way (not through cocoapods), and link it with `react-native link`.
* Make sure you see it under Libraries:
![image](https://cloud.githubusercontent.com/assets/83390/22691119/98bc6eca-ed41-11e6-90a0-8cb79bc235cf.png)
* Then make sure it's linked under "Linked Frameworks and Libraries" in your app's target.
* Now comes a little more tricky part. Clone lottie into the `ios` folder, and in Xcode, add it to the Libraries group.
![image](https://cloud.githubusercontent.com/assets/83390/22691320/8bccff26-ed42-11e6-8f4c-c9e05daf7276.png)
* Since we want it to compile before LottieReactNative, let's force this in build configuration, so "Edit Scheme...":
![image](https://cloud.githubusercontent.com/assets/83390/22691365/d5ac2798-ed42-11e6-820a-08bf81056843.png)
* Now go to Lottie.xcodeproj, and configure the headers:
![image](https://cloud.githubusercontent.com/assets/83390/22691393/f825ff24-ed42-11e6-8541-688613bdedb9.png)
* Remove the framework target, and add a static library target:
![image](https://cloud.githubusercontent.com/assets/83390/22691437/1e7855aa-ed43-11e6-823c-349305ddc1e9.png)
* On the right pane, make sure all files in the Lottie project are marked to be included in target:
![image](https://cloud.githubusercontent.com/assets/83390/22691420/107f2370-ed43-11e6-8722-cb886ce09801.png)
* Lastly, make sure the headers path is this:
![image](https://cloud.githubusercontent.com/assets/83390/22691471/528d0d86-ed43-11e6-9552-b794304f3e2f.png)

Hope this helps!

There might be redundant steps or a better way to do this, but this is the result of just plowing through and get it to work so that I can test the limits of Lottie and React Native. Obviously what ever @lelandrichardson is planning will be more elegant :).

**Comment by lelandrichardson** [comment]
This should work in updated versions now with no extra steps except what's listed in the README. Please let me know if you're having trouble!
