### ISSUE TITLE
iOS with cocoapods error - "Unknown receiver 'LAAnimationView'; did you mean 'LOTAnimationView'?"

### ISSUE THREAD

**Issue by Nirsky** [airbnb/lottie-react-native#57]
On version 1.0.5 - I'm getting the specified error (`Unknown receiver 'LAAnimationView'; did you mean 'LOTAnimationView'?`) when trying to run my project from Xcode.
The problematic file is: 

> myProject/node_modules/lottie-react-native/lib/ios/LottieReactNative

When replacing all occurrences of `LAAnimationView` with `LOTAnimationView` the project compiles and I'm able to display animations correctly. 
But still I can't use it this way since the repo is shared by a lot of developers and every `npm install` will result in compilation error.

Any solution?

**Comment by rjaylwar** [comment]
I am seeing the same issue

**Comment by jalpedersen** [comment]
The lottie-ios team made some name changes about 5 days ago. I opened a pull-request about 4 days ago, and unless there is some subtle detail I'm missing, the fix is trivial

**Comment by lelandrichardson** [comment]
Fixed in 1.0.6

**Comment by samcorcos** [comment]
Thanks @lelandrichardson, that did solve the error, however I am now getting a new error:

```
.../node_modules/lottie-react-native/lib/ios/LottieReactNative/LRNAnimationViewManager.m:57:37: 
error: incompatible block pointer types sending 'void (^)(RCTUIManager *__strong, 
NSDictionary<NSNumber *,UIView *> *__strong)' to parameter of type 'RCTViewManagerUIBlock' 
(aka 'void (^)(RCTUIManager *__strong, RCTSparseArray *__strong)')
```

I have no idea what to make of this one (I'm not an Obj-C developer).

**Comment by CodogoFreddie** [comment]
Still an issue for me, on master and v1.0.6 in `lottie-react-native/lib/ios/LottieReactNative/LRNContainerView.m` and `lottie-react-native/example/ios/Pods/Headers/Public/lottie-ios/Lottie/LAAnimationView.h`.

Any Ideas?

**Comment by amirmi** [comment]
Doesn't work for me either, I got the issue in the subject, "auto-fix"ed it by replacing LA with LOT.
and then I got what @samcorcos has...

any news?

**Comment by onpaws** [comment]
@lelandrichardson I'm encountering a similar issue, but the naming is the other way around. More over at #79
