### ISSUE TITLE
Cannot build on React Native 0.41.2

### ISSUE THREAD

**Issue by yoohoogun114** [airbnb/lottie-react-native#59]
# Current behavior:
Cannot build.

# Reproduce:
$ React native awesome
$ cd awesome
$ npm i --save lottie-react-native
```bash
└─┬ lottie-react-native@1.0.6 
  ├── lottie-ios@1.0.2 
  └─┬ react-native-safe-module@1.1.0 
    └── dedent@0.6.0 
```
$ react-native link lottie-ios
```bash
rnpm-install info Linking lottie-ios ios dependency 
rnpm-install info iOS module lottie-ios has been successfully linked 
```
$ react-native link lottie-react-native/
```bash
rnpm-install info Linking lottie-react-native/ android dependency 
rnpm-install info Android module lottie-react-native/ has been successfully linked 
rnpm-install info Linking lottie-react-native/ ios dependency 
rnpm-install info iOS module lottie-react-native/ has been successfully linked 
```

$ react-native run-ios
```bash
ld: warning: object file (/Users/yuhogyun/test/awesome/ios/build/Build/Products/Debug-iphonesimulator/libLottie.a(LOTAnimatableLayer.o)) was built for newer iOS version (10.2) than being linked (8.0)
ld: warning: object file (/Users/yuhogyun/test/awesome/ios/build/Build/Products/Debug-iphonesimulator/libLottie.a(LOTEllipseShapeLayer.o)) was built for newer iOS version (10.2) than being linked (8.0)
ld: warning: object file (/Users/yuhogyun/test/awesome/ios/build/Build/Products/Debug-iphonesimulator/libLottie.a(LOTGroupLayerView.o)) was built for newer iOS version (10.2) than being linked (8.0)
ld: warning: object file (/Users/yuhogyun/test/awesome/ios/build/Build/Products/Debug-iphonesimulator/libLottie.a(LOTLayerView.o)) was built for newer iOS version (10.2) than being linked (8.0)
ld: warning: object file (/Users/yuhogyun/test/awesome/ios/build/Build/Products/Debug-iphonesimulator/libLottie.a(LOTMaskLayer.o)) was built for newer iOS version (10.2) than being linked (8.0)
ld: warning: object file (/Users/yuhogyun/test/awesome/ios/build/Build/Products/Debug-iphonesimulator/libLottie.a(LOTRectShapeLayer.o)) was built for newer iOS version (10.2) than being linked (8.0)
ld: warning: object file (/Users/yuhogyun/test/awesome/ios/build/Build/Products/Debug-iphonesimulator/libLottie.a(LOTShapeLayerView.o)) was built for newer iOS version (10.2) than being linked (8.0)
ld: warning: object file (/Users/yuhogyun/test/awesome/ios/build/Build/Products/Debug-iphonesimulator/libLottie.a(LOTAnimatableBoundsValue.o)) was built for newer iOS version (10.2) than being linked (8.0)
ld: warning: object file (/Users/yuhogyun/test/awesome/ios/build/Build/Products/Debug-iphonesimulator/libLottie.a(LOTAnimatableColorValue.o)) was built for newer iOS version (10.2) than being linked (8.0)
ld: warning: object file (/Users/yuhogyun/test/awesome/ios/build/Build/Products/Debug-iphonesimulator/libLottie.a(LOTAnimatableNumberValue.o)) was built for newer iOS version (10.2) than being linked (8.0)
ld: warning: object file (/Users/yuhogyun/test/awesome/ios/build/Build/Products/Debug-iphonesimulator/libLottie.a(LOTAnimatablePointValue.o)) was built for newer iOS version (10.2) than being linked (8.0)
ld: warning: object file (/Users/yuhogyun/test/awesome/ios/build/Build/Products/Debug-iphonesimulator/libLottie.a(LOTAnimatableScaleValue.o)) was built for newer iOS version (10.2) than being linked (8.0)
ld: warning: object file (/Users/yuhogyun/test/awesome/ios/build/Build/Products/Debug-iphonesimulator/libLottie.a(LOTAnimatableShapeValue.o)) was built for newer iOS version (10.2) than being linked (8.0)
ld: warning: object file (/Users/yuhogyun/test/awesome/ios/build/Build/Products/Debug-iphonesimulator/libLottie.a(LOTShapeRectangle.o)) was built for newer iOS version (10.2) than being linked (8.0)
ld: warning: object file (/Users/yuhogyun/test/awesome/ios/build/Build/Products/Debug-iphonesimulator/libLottie.a(LOTAnimationCache.o)) was built for newer iOS version (10.2) than being linked (8.0)
ld: warning: object file (/Users/yuhogyun/test/awesome/ios/build/Build/Products/Debug-iphonesimulator/libLottie.a(LOTComposition.o)) was built for newer iOS version (10.2) than being linked (8.0)
ld: warning: object file (/Users/yuhogyun/test/awesome/ios/build/Build/Products/Debug-iphonesimulator/libLottie.a(LOTShapeGroup.o)) was built for newer iOS version (10.2) than being linked (8.0)
ld: warning: object file (/Users/yuhogyun/test/awesome/ios/build/Build/Products/Debug-iphonesimulator/libLottie.a(LOTMask.o)) was built for newer iOS version (10.2) than being linked (8.0)
ld: warning: object file (/Users/yuhogyun/test/awesome/ios/build/Build/Products/Debug-iphonesimulator/libLottie.a(LOTShapeStroke.o)) was built for newer iOS version (10.2) than being linked (8.0)
ld: warning: object file (/Users/yuhogyun/test/awesome/ios/build/Build/Products/Debug-iphonesimulator/libLottie.a(LOTLayer.o)) was built for newer iOS version (10.2) than being linked (8.0)
ld: warning: object file (/Users/yuhogyun/test/awesome/ios/build/Build/Products/Debug-iphonesimulator/libLottie.a(LOTAnimationView.o)) was built for newer iOS version (10.2) than being linked (8.0)
ld: warning: object file (/Users/yuhogyun/test/awesome/ios/build/Build/Products/Debug-iphonesimulator/libLottie.a(LOTShapePath.o)) was built for newer iOS version (10.2) than being linked (8.0)
ld: warning: object file (/Users/yuhogyun/test/awesome/ios/build/Build/Products/Debug-iphonesimulator/libLottie.a(LOTShapeTransform.o)) was built for newer iOS version (10.2) than being linked (8.0)
ld: warning: object file (/Users/yuhogyun/test/awesome/ios/build/Build/Products/Debug-iphonesimulator/libLottie.a(LOTShapeFill.o)) was built for newer iOS version (10.2) than being linked (8.0)
ld: warning: object file (/Users/yuhogyun/test/awesome/ios/build/Build/Products/Debug-iphonesimulator/libLottie.a(LOTShapeTrimPath.o)) was built for newer iOS version (10.2) than being linked (8.0)
ld: warning: object file (/Users/yuhogyun/test/awesome/ios/build/Build/Products/Debug-iphonesimulator/libLottie.a(LOTShapeCircle.o)) was built for newer iOS version (10.2) than being linked (8.0)
ld: warning: object file (/Users/yuhogyun/test/awesome/ios/build/Build/Products/Debug-iphonesimulator/libLottie.a(CAAnimationGroup+LOTAnimatableGroup.o)) was built for newer iOS version (10.2) than being linked (8.0)
ld: warning: object file (/Users/yuhogyun/test/awesome/ios/build/Build/Products/Debug-iphonesimulator/libLottie.a(CGGeometryAdditions.o)) was built for newer iOS version (10.2) than being linked (8.0)
ld: warning: object file (/Users/yuhogyun/test/awesome/ios/build/Build/Products/Debug-iphonesimulator/libLottie.a(UIColor+Expanded.o)) was built for newer iOS version (10.2) than being linked (8.0)
ld: warning: object file (/Users/yuhogyun/test/awesome/ios/build/Build/Products/Debug-iphonesimulator/libLottie.a(LOTAnimationTransitionController.o)) was built for newer iOS version (10.2) than being linked (8.0)
ld: warning: object file (/Users/yuhogyun/test/awesome/ios/build/Build/Products/Debug-iphonesimulator/libLottie.a(Lottie_vers.o)) was built for newer iOS version (10.2) than being linked (8.0)
Undefined symbols for architecture x86_64:
  "_OBJC_CLASS_$_LOTStrokeShapeLayer", referenced from:
      _OBJC_CLASS_$_LOTCircleShapeLayer in libLottie.a(LOTEllipseShapeLayer.o)
      _OBJC_CLASS_$_LOTRoundRectLayer in libLottie.a(LOTRectShapeLayer.o)
      objc-class-ref in libLottie.a(LOTShapeLayerView.o)
  "_OBJC_METACLASS_$_LOTStrokeShapeLayer", referenced from:
      _OBJC_METACLASS_$_LOTCircleShapeLayer in libLottie.a(LOTEllipseShapeLayer.o)
      _OBJC_METACLASS_$_LOTRoundRectLayer in libLottie.a(LOTRectShapeLayer.o)
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)


** BUILD FAILED **


The following commands produced analyzer issues:
	Analyze Modules/RCTRedBox.m
(1 command with analyzer issues)


The following build commands failed:
	Ld build/Build/Products/Debug-iphonesimulator/awesome.app/awesome normal x86_64
(1 failure)

Installing build/Build/Products/Debug-iphonesimulator/awesome.app
An error was encountered processing the command (domain=NSPOSIXErrorDomain, code=22):
Failed to install the requested application
The bundle identifier of the application could not be determined.
Ensure that the application's Info.plist contains a value for CFBundleIdentifier.
Print: Entry, ":CFBundleIdentifier", Does Not Exist

Command failed: /usr/libexec/PlistBuddy -c Print:CFBundleIdentifier build/Build/Products/Debug-iphonesimulator/awesome.app/Info.plist
Print: Entry, ":CFBundleIdentifier", Does Not Exist
```

So, I open my iOS project ,clean and then build

But error log here
```bash
Undefined symbols for architecture x86_64:
  "_OBJC_CLASS_$_LOTStrokeShapeLayer", referenced from:
      _OBJC_CLASS_$_LOTCircleShapeLayer in libLottie.a(LOTEllipseShapeLayer.o)
      _OBJC_CLASS_$_LOTRoundRectLayer in libLottie.a(LOTRectShapeLayer.o)
      objc-class-ref in libLottie.a(LOTShapeLayerView.o)
  "_OBJC_METACLASS_$_LOTStrokeShapeLayer", referenced from:
      _OBJC_METACLASS_$_LOTCircleShapeLayer in libLottie.a(LOTEllipseShapeLayer.o)
      _OBJC_METACLASS_$_LOTRoundRectLayer in libLottie.a(LOTRectShapeLayer.o)
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

My environment is OS X Elcapitan 10.11

$ node -v
```bash
v7.5.0
```

$ npm -v
```bash
4.1.2
```

$ react-native -v
```bash
react-native-cli: 2.0.1
react-native: 0.41.2
```

# Comment
The recent lottie-ios is 1.0.3 but lottie-react-native dependency ios is 1.0.2

Is it related to the version dependency?

# Editted
$ react-native upgrade

Then i can use lottie.

but animation not showing without any error.

**Comment by FMJaguar** [comment]
Same error here, temporarily fixed by creating a new project using the guide in #31

**Comment by jjhesk** [comment]
no animation here and I cannot build. #52

**Comment by leesolway** [comment]
Same error

**Comment by hugohow** [comment]
Same for me

**Comment by jozan** [comment]
I got it working by adding `Lottie.framework` to `Embedded Binaries` in XCode.

![image](https://cloud.githubusercontent.com/assets/388265/22987285/eb1f56d4-f3b6-11e6-962a-129d261e6e6c.png)

**Comment by yoohoogun114** [comment]
@jozan Awesome! It works for me

**Comment by hugohow** [comment]
@jozan  it workd for me too ;) Thanks !!

**Comment by yoohoogun114** [comment]
In more detail,
![2017-02-16 2 56 55](https://cloud.githubusercontent.com/assets/13046348/22988485/a23ac3f6-f3f5-11e6-9bc8-b98d426dcbd6.png)
![2017-02-16 2 57 17](https://cloud.githubusercontent.com/assets/13046348/22988495/ac4d1e20-f3f5-11e6-8efa-edc2f587aebd.png)

**Comment by leesolway** [comment]
Worked for me also, thanks.

**Comment by yoohoogun114** [comment]
It Resolved For me, so closed

**Comment by leesolway** [comment]
Its still a bug though and needs to be resolve, doesn't it?

**Comment by beiming** [comment]
@yoohoogun114 Same error. and solved by your answer. 
But I have new error:
1. Can not run `react-native run-ios`  to start simulator, build success, run crash.
2. Launch simulator from Xcode, no error. but not show animation.

Do you have same question?

**Comment by leesolway** [comment]
I had the same experience. I can compile, but no animation or image rendering.

**Comment by olle-moren-schibsted** [comment]
I've RN 0.39.2 and been trying all guides here, still having the same error á `'Lottie/Lottie.h' file not found` inside `node_modules/lottie-react-native/lib/ios/LottieReactNative/LRNContainerView.h`
Do you guys think it's RN 0.39.2 being the bad guy?

**Comment by indivisable** [comment]
@leesolway same here, trying to figure out why rendering is not working (https://github.com/airbnb/lottie-react-native/issues/52)

**Comment by yoohoogun114** [comment]
It works for me, but looks like not others. so Reopen.

**Comment by jozan** [comment]
@olle-moren-schibsted Are you sure you have linked `lottie-ios`as well?

`react-native link lottie-ios`

**Comment by olle-moren-schibsted** [comment]
@jozan having node version 6.5.0 and RN 0.39.2 doing like this:
```npm i --save lottie-react-native
rn@0.0.1
└─┬ lottie-react-native@1.0.6
  ├── lottie-ios@1.0.2
  └─┬ react-native-safe-module@1.1.0
    └── dedent@0.6.0

react-native link lottie-ios
rnpm-install info Linking lottie-ios ios dependency
rnpm-install info iOS module lottie-ios has been successfully linked
react-native link lottie-react-native
rnpm-install info Linking lottie-react-native android dependency
rnpm-install info Android module lottie-react-native has been successfully linked
rnpm-install info Linking lottie-react-native ios dependency
rnpm-install info iOS module lottie-react-native has been successfully linked```
![xcode](https://cloud.githubusercontent.com/assets/5330517/23119669/700e2d52-f759-11e6-9551-ccc29ebd50fc.png)

**Comment by jozan** [comment]
@olle-moren-schibsted Those are the steps I got it working on RN 0.41.2.

**Comment by PanJ** [comment]
For anyone that is still having problem. Error is something like this

```
Class LOTStrokeShapeLayer is implemented in both
...
...
```

This can be fixed by deleting `libLottie.a` and adding `Lottie.framework` in the embeded binaries section instead. The final linked libraries should be like this.

![image](https://cloud.githubusercontent.com/assets/1797879/23450625/c962834e-fe8e-11e6-9cdb-760757dc0763.png)

**Comment by g3r4n** [comment]
Thanks @PanJ !

**Comment by kyle-ssg** [comment]
Can this be added to the readme?

**Comment by g3r4n** [comment]
@kyle-ssg see PR #86

**Comment by jjhesk** [comment]
It is working only if this condition is met and correctly linked: 
Embedded binary + Lottie.framework
Link Frameworks and LIbrary +  libLottieReactNative.a

**Comment by leesolway** [comment]
I had both of these, but was still getting a blank image where the animation should have been.

**Comment by g3r4n** [comment]
@leesolway Can you confirm that LibLottie.a isn't linked ? Can you provide a screenshot of your Embedded binary and Link Frameworks and LIbrary ?

**Comment by Kowaio** [comment]
Hi guys,

Posting here because I've got a similar problem. I succeeded to make lottie work on my RN project using Lottie 1.0.6 and RN 0.39 on iOS in debug. I removed`libLottie.a` as said above from the linked frameworks and libraries and it's building well on the simulator and animations correctly appear.

However, when using fastlane to generate an .ipa to deploy on Testflight for my team, the build is not working and I've got the following message `node_modules/lottie-react-native/lib/ios/LottieReactNative/LRNContainerView.h:19:9: 'Lottie/Lottie.h' file not found`
http://cl.kowaio.me/2w0M2027462S

I don't know why it's doing this in release since everything seems to work. Did you encounter this while trying to build on your side?

Thanks again guys

**Comment by g3r4n** [comment]
@Kowaio seems like you don't have link the Lottie.Framework. Can you provide a screenshot of your Embedded binary and Link Frameworks and LIbrary ?

**Comment by g3r4n** [comment]
@Kowaio can't help sorry. Maybe see [this comment](https://github.com/airbnb/lottie-react-native/issues/89#issuecomment-286562123).
Open a proper issue to get more accurate help.

**Comment by leesolway** [comment]
![screen shot 2017-03-16 at 12 29 57](https://cloud.githubusercontent.com/assets/2929803/23996185/6afeef9c-0a44-11e7-9f6e-e80dbd6dcd7d.png)

@g3r4n 

As requested

**Comment by lelandrichardson** [comment]
I believe this should now be fixed in `lottie-react-native@1.1.1`. Please try it out and let me know if you still have trouble. Closing this issue for now. Thanks!

**Comment by Kowaio** [comment]
Hello @lelandrichardson,

Sorry to come back to you only now. I tested with `lottie-react-native@1.1.1` but I've got the same problem while building for release.

Here's a screenshot: http://cl.ly/0s0U1a211f2j

Thanks

**Comment by YouDuk** [comment]
@Kowaio same here.
